sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug':
            secret_key: &secretKey
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/secret_key.html.twig'
                priority: 0
            one_click:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/one_click.html.twig'
                priority: 0
            integrated_payment:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/integrated_payment.html.twig'
                priority: 0
            deferred_capture:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/deferred_capture.html.twig'
                priority: 0
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_oney':
            secret_key: *secretKey
            fees_for:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/fees_for.html.twig'
                priority: 0
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_bancontact':
            secret_key: *secretKey
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_apple_pay':
            secret_key: *secretKey
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_american_express':
            secret_key: *secretKey
