sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug': &payplugGateway
            live_checkbox: &liveCheckbox
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/live_checkbox.html.twig'
                priority: 0
            one_click:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/one_click.html.twig'
                priority: 0
            integrated_payment:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/integrated_payment.html.twig'
                priority: 0
            deferred_capture:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/deferred_capture.html.twig'
                priority: 0
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_oney': &oneyGateway
            live_checkbox: *liveCheckbox
            fees_for:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/fees_for.html.twig'
                priority: 0
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_bancontact': &bancontactGateway
            live_checkbox: *liveCheckbox
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_apple_pay': &applePayGateway
            live_checkbox: *liveCheckbox

        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_american_express': &amexGateway
            live_checkbox: *liveCheckbox

        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.payplug':
            <<: *payplugGateway
            renew_oauth: &renewOAuth
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/renew_oauth.html.twig'
                priority: -5
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.payplug_oney':
            <<: *oneyGateway
            renew_oauth: *renewOAuth
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.payplug_bancontact':
            <<: *bancontactGateway
            renew_oauth: *renewOAuth
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.payplug_apple_pay':
            <<: *applePayGateway
            renew_oauth: *renewOAuth
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.payplug_american_express':
            <<: *amexGateway
            renew_oauth: *renewOAuth
