sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug': &payplugGateway
            secret_key: &secretKey
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/secret_key.html.twig'
                priority: 0
            one_click:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/one_click.html.twig'
                priority: 0
            integrated_payment:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/integrated_payment.html.twig'
                priority: 0
            deferred_capture:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/deferred_capture.html.twig'
                priority: 0
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_oney': &oneyGateway
            secret_key: *secretKey
            fees_for:
                template: '@PayPlugSyliusPayPlugPlugin/admin/payment_method/form/fees_for.html.twig'
                priority: 0
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_bancontact': &bancontactGateway
            secret_key: *secretKey
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_apple_pay': &applePayGateway
            secret_key: *secretKey
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.payplug_american_express': &amexGateway
            secret_key: *secretKey

        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.payplug': *payplugGateway
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.payplug_oney': *oneyGateway
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.payplug_bancontact': *bancontactGateway
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.payplug_apple_pay': *applePayGateway
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.payplug_american_express': *amexGateway