sylius_twig_hooks:
    hooks:
        'sylius_shop.product.show.content.info.summary':
            pay_with_oney:
                template: '@PayPlugSyliusPayPlugPlugin/oney/product/pay_with_oney.html.twig'
                priority: 101
        'sylius_shop.cart.index.content.form.sections.general#right':
            pay_with_oney:
                template: '@PayPlugSyliusPayPlugPlugin/oney/cart/pay_with_oney.html.twig'
                priority: 1
        'sylius_shop.account.saved_card#stylesheets':
            payplug_styles:
                template: '@PayPlugSyliusPayPlugPlugin/stylesheets/saved_cards.html.twig'
                priority: 1
        'sylius.shop.account.saved_cards.index.subcontent':
            header:
                template: '@PayPlugSyliusPayPlugPlugin/Account/SavedCards/Index/_header.html.twig'
                priority: 20
            subcontent:
                template: "@PayPlugSyliusPayPlugPlugin/Account/SavedCards/Index/_subcontent.html.twig"
                priority: 10
