sylius_twig_hooks:
    hooks:
        'sylius_shop.product.show.content.info.summary':
            pay_with_oney:
                template: '@PayPlugSyliusPayPlugPlugin/oney/product/pay_with_oney.html.twig'
                priority: 101
        'sylius_shop.cart.index.content.form.sections.general#right':
            pay_with_oney:
                template: '@PayPlugSyliusPayPlugPlugin/oney/cart/pay_with_oney.html.twig'
                priority: 1