sylius_twig_hooks:
    hooks:
        'sylius_shop.base#stylesheets':
            payplug_styles:
                template: '@PayPlugSyliusPayPlugPlugin/stylesheets/saved_cards.html.twig'
                priority: 1
        'sylius.shop.account.saved_cards.index.subcontent':
            header:
                template: '@SyliusShop/Account/SavedCards/Index/_header.html.twig'
                priority: 20
            subcontent:
                template: "@SyliusShop/Account/SavedCards/Index/_subcontent.html.twig"
                priority: 10

        'sylius_shop.shared.form.select_payment.payment.choice.details':
            select_payment_css:
                template: '@PayPlugSyliusPayPlugPlugin/stylesheets/select_payment_css.html.twig'
