services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    PayPlug\SyliusPayPlugPlugin\:
        resource: '../src/*'
        exclude: '../src/{ApiClient,DependencyInjection,Entity,Exception,Gateway,Model,Repository,PayPlugSyliusPayPlugPlugin.php}'

    PayPlug\SyliusPayPlugPlugin\Repository\PaymentRepositoryInterface:
        class: PayPlug\SyliusPayPlugPlugin\Repository\PaymentRepository
        parent: sylius.repository.payment

    PayPlug\SyliusPayPlugPlugin\Repository\PaymentMethodRepositoryInterface:
        class: PayPlug\SyliusPayPlugPlugin\Repository\PaymentMethodRepository
        parent: sylius.repository.payment_method

    PayPlug\SyliusPayPlugPlugin\Controller\OrderController:
        parent: sylius.controller.order

    PayPlug\SyliusPayPlugPlugin\Provider\OneySimulation\OneySimulationDataProviderInterface:
        class: PayPlug\SyliusPayPlugPlugin\Provider\OneySimulation\OneySimulationDataProvider

    payplug_sylius_payplug_plugin.action.capture:
        class: PayPlug\SyliusPayPlugPlugin\Action\CaptureAction

    payplug_sylius_payplug_plugin.action.status:
        class: PayPlug\SyliusPayPlugPlugin\Action\StatusAction

    payplug_sylius_payplug_plugin.action.convert_payment:
        class: PayPlug\SyliusPayPlugPlugin\Action\ConvertPaymentAction

    payplug_sylius_payplug_plugin.action.notify:
        class: PayPlug\SyliusPayPlugPlugin\Action\NotifyAction
