sylius_ui:
    events:
        sylius.shop.product.show.right_sidebar:
            blocks:
                pay_with_oney:
                    template: '@PayPlugSyliusPayPlugPlugin/oney/product/pay_with_oney.html.twig'
                    priority: 29 # After price widget
                    context:
                        legacy_event: 'sonata.block.event.sylius.shop.product.show.after_price'
        sylius.shop.cart.summary.totals:
            blocks:
                pay_with_oney:
                    template: '@PayPlugSyliusPayPlugPlugin/oney/cart/pay_with_oney.html.twig'
        sylius.shop.layout.javascripts:
            blocks:
                webfontloader:
                    template: '@PayPlugSyliusPayPlugPlugin/javascripts/webfont_loader.html.twig'
                oney_common:
                    template: '@PayPlugSyliusPayPlugPlugin/javascripts/oney_common.html.twig'
        sylius.shop.layout.stylesheets:
            blocks:
                oney_common:
                    template: '@PayPlugSyliusPayPlugPlugin/stylesheets/oney_common.html.twig'
        sylius.admin.payment_method.create.stylesheets: &cssEvt
            blocks:
                payment_methods_css:
                    template: '@PayPlugSyliusPayPlugPlugin/stylesheets/payment_method_css.html.twig'
        sylius.admin.payment_method.update.stylesheets: *cssEvt
        sylius.shop.checkout.select_payment.before_form: &selectPayment
            blocks:
                select_payment_js:
                    template: '@PayPlugSyliusPayPlugPlugin/javascripts/select_payment_js.html.twig'
        sylius.shop.order.select_payment.before_form: *selectPayment
