parameters:
    sylius_refund.supported_gateways:
        - payplug
        - payplug_oney
        - cash_on_delivery

services:
    payplug_sylius_payplug_plugin.api_client.payplug:
        class: Tests\PayPlug\SyliusPayPlugPlugin\Behat\Mocker\PayPlugApiClient
        public: true
        arguments:
            - "@service_container"
            - 'payplug_sylius_payplug_plugin.api_client.payplug'

    payplug_sylius_payplug_plugin.api_client.oney:
        class: Tests\PayPlug\SyliusPayPlugPlugin\Behat\Mocker\PayPlugApiClient
        public: true
        arguments:
            - "@service_container"
            - 'payplug_sylius_payplug_plugin.api_client.oney'

    PayPlug\SyliusPayPlugPlugin\ApiClient\PayPlugApiClientFactoryInterface:
        class: Tests\PayPlug\SyliusPayPlugPlugin\Behat\Mocker\PayPlugApiClientFactory
        public: true
        arguments:
            - "@service_container"
            - "payplug_sylius_payplug_plugin.api_client.payplug"

    Tests\Sylius\RefundPlugin\Behat\Services\Generator\FailedCreditMemoGenerator:
        decorates: 'Sylius\RefundPlugin\Generator\CreditMemoGeneratorInterface'
        arguments:
            - '@Tests\Sylius\RefundPlugin\Behat\Services\Generator\FailedCreditMemoGenerator.inner'

    Tests\Sylius\RefundPlugin\Behat\Services\Factory\FailedRefundPaymentFactory:
        decorates: 'sylius_refund.factory.refund_payment'
        arguments:
            - '@Tests\Sylius\RefundPlugin\Behat\Services\Factory\FailedRefundPaymentFactory.inner'
