winzou_state_machine:
    sylius_payment:
        callbacks:
            before:
                payplug_sylius_payplug_plugin_refund_process:
                    on: ["refund"]
                    do: ["@PayPlug\\SyliusPayPlugPlugin\\PaymentProcessing\\RefundPaymentHandler", "process"]
                    args: ["object"]
                payplug_sylius_payplug_plugin_failed_process:
                    on: ["fail"]
                    do: ["@PayPlug\\SyliusPayPlugPlugin\\PaymentProcessing\\AbortPaymentProcessor", "process"]
                    args: ["object"]
                payplug_sylius_payplug_plugin_complete:
                    on: ["complete"]
                    do: ["@PayPlug\\SyliusPayPlugPlugin\\PaymentProcessing\\CaptureAuthorizedPaymentProcessor", "process"]
                    args: ["object"]
